sudo: false

language: go

go:
  - 1.13.x

git:
  depth: 1

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/smartystreets/goconvey/convey

env: GO111MODULE=on GOFLAGS='-mod vendor'

env:
  global:
    - secure: "KAujr5mge2CMsYFG8e1+I2ACZqsWRwF1pqqnDJ3AVZed6UbdT/1yPYyT2RO1JknVXCOi83h+Psf31AWVlO7IbEPLCwG5xDo5AJnNdnsNn9mTVd/ukiscJB6UWxOeCXTW6kUmd+5W72GIqlbgQb8xaTAbMpu6t+5cH1lRXoN+Osk="

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS

secure: "KAujr5mge2CMsYFG8e1+I2ACZqsWRwF1pqqnDJ3AVZed6UbdT/1yPYyT2RO1JknVXCOi83h+Psf31AWVlO7IbEPLCwG5xDo5AJnNdnsNn9mTVd/ukiscJB6UWxOeCXTW6kUmd+5W72GIqlbgQb8xaTAbMpu6t+5cH1lRXoN+Osk="
