sudo: false

language: go

go:
  - 1.2
  - 1.3
  - 1.3.3
  - 1.4
  - 1.4.2

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/smartystreets/goconvey/convey

env:
  global:
    - secure: "KAujr5mge2CMsYFG8e1+I2ACZqsWRwF1pqqnDJ3AVZed6UbdT/1yPYyT2RO1JknVXCOi83h+Psf31AWVlO7IbEPLCwG5xDo5AJnNdnsNn9mTVd/ukiscJB6UWxOeCXTW6kUmd+5W72GIqlbgQb8xaTAbMpu6t+5cH1lRXoN+Osk="

script:
  - goveralls -repotoken $COVERALLS

secure: "KAujr5mge2CMsYFG8e1+I2ACZqsWRwF1pqqnDJ3AVZed6UbdT/1yPYyT2RO1JknVXCOi83h+Psf31AWVlO7IbEPLCwG5xDo5AJnNdnsNn9mTVd/ukiscJB6UWxOeCXTW6kUmd+5W72GIqlbgQb8xaTAbMpu6t+5cH1lRXoN+Osk="
